[[chains]]
name = "osmosis-testnet"
gas_denom = "uosmo"
gas_prices = "0.025uosmo"
gas_multiplier = 1.3
keyring_backend = "test"
keyring_app_name = "osmosis"
keyring_root_dir = "/home/margined/.osmosisd"
keyring_uid = "osmo-5-treasury"
grpc_url = "osmosis-testnet-grpc.polkachu.com:12590"
accounts = [
  "osmo19z9j3240alpa2xl0h4epvr5vryjmam6w3pwm4h",
  "osmo1sut9jhaxsvc3lnps7jzu5pmh4n0kpzfsq0depx",
  "osmo1tj0zhw2sqtvy43gzjqh6r6wff9zykfwcyut3ez",
  "osmo1ys5lj28zrvpm9cjj0958awqmjt8aa8vpdflqc2",
  "osmo1yrg6daqkxyeqye4aac09stzvvwppqwls6wgpxr",
]
threshold = 1000000
amount_to_fund = 5000000
frequency = 3
