on: 
  push

name: Test

jobs:
  test:
    strategy:
      matrix:
        project: [neutron]
        go-version: [1.23.x]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # Configure Git to use the GH_TOKEN for private repositories
    - name: Configure Git to use GitHub token
      run: git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com".insteadOf "https://github.com"
    
    # Setup Go environment
    - uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}
    
    # Cache Go modules
    - name: Cache Go modules
      id: cache-go-mod
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-mod-${{ matrix.go-version }}-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-${{ matrix.go-version }}-${{ runner.os }}-

    # Run tests for the current project
    - name: Run tests for ${{ matrix.project }}
      working-directory: ./${{ matrix.project }}
      run: make test

